name: Build and Deploy

on:
  push:
    branches:
      - develop

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  DOCKERHUB_USERNAME : ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1

      #Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Package Spring Application
        run: ./gradlew bootJar --no-daemon

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/ezvitrine-backend:latest

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Print environment variable
        run: echo ${{ vars.TEST_TOKEN }}


      - name: Print Railway Token
        run: echo " Print a single environment variable ${{ secrets.DEV_RAILWAY_TOKEN }} "
